services:
  myngl-jaeger:
    container_name: jaeger
    restart: unless-stopped
    image: jaegertracing/all-in-one:latest
    ports:
    - "127.0.0.1:16686:16686"
    - "127.0.0.1:14268:14268"
    - "127.0.0.1:4317:4317"
    environment:
    - COLLECTOR_OTLP_ENABLED=true
    networks:
    - myngl-network    
  myngl-agent:
    container_name: myngl-agent
    hostname: myngl-agent
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3030:3030"
    networks:
      - myngl-network      
  myngl-agentgateway:
    image: cgthayer/agentgateway:latest
    command: ["-f", "/app/config/agentgateway-config.yaml"]
    env_file:
      - .env
    hostname: agentgateway
    volumes:
      - ./:/app/config
    ports:
      - "3010:3010"
      - "15000:15000"
    networks:
      - myngl-network
      - public-network

networks:
  public-network:
    driver: bridge
  myngl-network:
    driver: bridge
